// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TempSocketServer/Dish.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from TempSocketServer/Dish.proto</summary>
public static partial class DishReflection {

  #region Descriptor
  /// <summary>File descriptor for TempSocketServer/Dish.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static DishReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChtUZW1wU29ja2V0U2VydmVyL0Rpc2gucHJvdG8iPQoERGlzaBIMCgRuYW1l",
          "GAEgASgJEhEKCWRldmVsb3BlchgCIAEoCRIUCgxyZWxlYXNlX3llYXIYAyAB",
          "KAUiOwoLUHJlbWl1bURpc2gSDAoEbmFtZRgBIAEoCRIPCgdxdWFsaXR5GAIg",
          "ASgJEg0KBXByaWNlGAMgASgFQgJIAWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Dish), global::Dish.Parser, new[]{ "Name", "Developer", "ReleaseYear" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PremiumDish), global::PremiumDish.Parser, new[]{ "Name", "Quality", "Price" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Dish : pb::IMessage<Dish> {
  private static readonly pb::MessageParser<Dish> _parser = new pb::MessageParser<Dish>(() => new Dish());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Dish> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DishReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Dish() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Dish(Dish other) : this() {
    name_ = other.name_;
    developer_ = other.developer_;
    releaseYear_ = other.releaseYear_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Dish Clone() {
    return new Dish(this);
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 1;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "developer" field.</summary>
  public const int DeveloperFieldNumber = 2;
  private string developer_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Developer {
    get { return developer_; }
    set {
      developer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "release_year" field.</summary>
  public const int ReleaseYearFieldNumber = 3;
  private int releaseYear_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int ReleaseYear {
    get { return releaseYear_; }
    set {
      releaseYear_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Dish);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Dish other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Name != other.Name) return false;
    if (Developer != other.Developer) return false;
    if (ReleaseYear != other.ReleaseYear) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (Developer.Length != 0) hash ^= Developer.GetHashCode();
    if (ReleaseYear != 0) hash ^= ReleaseYear.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (Developer.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Developer);
    }
    if (ReleaseYear != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(ReleaseYear);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (Developer.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Developer);
    }
    if (ReleaseYear != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ReleaseYear);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Dish other) {
    if (other == null) {
      return;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.Developer.Length != 0) {
      Developer = other.Developer;
    }
    if (other.ReleaseYear != 0) {
      ReleaseYear = other.ReleaseYear;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 18: {
          Developer = input.ReadString();
          break;
        }
        case 24: {
          ReleaseYear = input.ReadInt32();
          break;
        }
      }
    }
  }

}

public sealed partial class PremiumDish : pb::IMessage<PremiumDish> {
  private static readonly pb::MessageParser<PremiumDish> _parser = new pb::MessageParser<PremiumDish>(() => new PremiumDish());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<PremiumDish> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DishReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PremiumDish() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PremiumDish(PremiumDish other) : this() {
    name_ = other.name_;
    quality_ = other.quality_;
    price_ = other.price_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public PremiumDish Clone() {
    return new PremiumDish(this);
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 1;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "quality" field.</summary>
  public const int QualityFieldNumber = 2;
  private string quality_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Quality {
    get { return quality_; }
    set {
      quality_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "price" field.</summary>
  public const int PriceFieldNumber = 3;
  private int price_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Price {
    get { return price_; }
    set {
      price_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as PremiumDish);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(PremiumDish other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Name != other.Name) return false;
    if (Quality != other.Quality) return false;
    if (Price != other.Price) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (Quality.Length != 0) hash ^= Quality.GetHashCode();
    if (Price != 0) hash ^= Price.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (Quality.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Quality);
    }
    if (Price != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Price);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (Quality.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Quality);
    }
    if (Price != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Price);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(PremiumDish other) {
    if (other == null) {
      return;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.Quality.Length != 0) {
      Quality = other.Quality;
    }
    if (other.Price != 0) {
      Price = other.Price;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 18: {
          Quality = input.ReadString();
          break;
        }
        case 24: {
          Price = input.ReadInt32();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
